### ISSUE TITLE
Save file 

### ISSUE THREAD

**Issue by Zen0x7** [kurt-weber/hzswitch#1]
Hi kurt, 

I'm young developer, without python knowledge. i'm finding a solution to convert audio from 440hz to 432hz, because i want to make a open source command-line interface. 

I think this can be really helpful to music creators. i have a friend who make too many steps to convert music, so i want to automatice these tasks.

I'll study your code to try to understand how it works.

If you have information, documentation, whatever can help me, thanks.

**Comment by kurt-weber** [comment]
Hi Ian,

so you wanna convert music files permanently? In this case have a look at audacity. Maybe its possible to control it via command line to.

**Comment by Zen0x7** [comment]
Hi again,

After a good search on GH, i discover this documentation... at the footer (example #6) he explains how to reduce semitones to get 432 hz.

https://github.com/owoudenberg/soundtouch.net/wiki/SoundStretch-audio-processing-utility

So, yeah, audacity is the common solution, but i was looking a CLI... 

Thanks for your time kurt. You're free to close this issue.
