### ISSUE TITLE
Why don't you reverse this as well?

### ISSUE THREAD

**Issue by pshhhhhh** [kurt-weber/hzswitch#3]
Could you make the reverse 432Hz to 440Hz available as well please?  Some people would like to play over 432Hz music on-the-fly but are stuck in 440 with their instrument.  Thanks a bunch! 

PS- I would write it myself, if I weren't dumb.

**Comment by kurt-weber** [comment]
Considering you can tune your instrument to your liking anyhow this sounds completely useless.

If you still want to try it just change this line in hzswitch.py from
self.pitch_element.props.pitch = 0.98182
to
self.pitch_element.props.pitch = 1.01852

this will result in changing 432Hz to 440Hz

**Comment by pshhhhhh** [comment]
HEY!   Thanks so much for getting back tome and answering this with a solution!!!  That was really nice of you. =DThe reason I suggested you add it your code and GUI was for people who want this function badly.  lolThere are music streamers on Twitch that would probably pay a little money for this, if it actually worked well!  The reason being is that they play over song requests to entertain people and make money for themselves, but a good portion of those song requests are in 432 and the streamer can't play them. So they potentially lose a donation for playing the song, they don't want to retune their instruments to play a song, to have to retune for the next song.  They play requests back to back.So, if your code actually works well ... ESPECIALLY for audio played from YouTube, or bandcamp, etc ... then that problem for Twitch music streamers would be solved.  You'd be a hero to many, making others money and so on....My suggestion to you is to release a special paid version of your free 432 app for Twitch music streamers 432 -> 440 version, and either give it away to be a kind hero, or charge a little bit for it, because it solved a major problem people were having.Also, be aware that many instruments are not tunable down to 432.  I know this for a fact, of saxophone in particular.  If I wanted to play 432 tunes on a tenor, I'd be forced to buy an expensive, specially made 432 tenor sax, or I'd have to use your code, which you've shared with me.  XDI'd suggest you redesign your GUI for Twitch, make sure it works well, and then sell it.  As your first customers (at a discounted, friends rate because of everything I've just shared with you) talk to the Twitch streamers, WaxWaneMusic, edplaysjazz, DarthGaddy, and SaraJazz, and offer your new app to them.  See how fast they buy it at a reasonable price.Hope I hear from you again, and thanks again for the solution!  <3 DrewSent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by kurt-weber** [comment]
Sorry you had to wait so long. I wanted to get rid of the big bug before making any further implementations.
I added the feature you wished for. Cheers
