### ISSUE TITLE
Little update

### ISSUE THREAD

**Issue by Jopp-gh** [kurt-weber/hzswitch#4]
Rhythmbox sees your plugin, but the checkbox to activate / deactivate your plugin does nothing, no buttons appear in Rhythmbox' UI as shown in your readme. 
Could you update your plugin, please?

**Comment by kurt-weber** [comment]
Sorry for the really really late answer.

I found two things that might cause this behavior.
1) A missing settings.ini, I added a default one two the current version

2) On a fresh installed rhythmbox you also have to install the package rhythmbox-plugins
sudo apt-get install rhythmbox-plugins

**Comment by Jopp-gh** [comment]
O my! now it works like a charm,
thank you very much!  🙂
